//require('./sandbox/tests');
require('./slides/PureComponents');
require('./components/AppSpec');
require('./components/IbanSpec');
require('./components/SalarieCardSpec');
require('./components/CompteSwitcherSpec');
require('./components/SearchFilterSpec');
require('./components/VirementBoxSpec');
require('./components/MainSectionSpec');
